set_pns_commit_mode true
# Starting to commit core rings
create_power_straps  -direction vertical  -start_at 1952.590 -nets VDD -layer 62 -width 10.000 -start_low_ends coordinate  -start_low_ends_coordinate 210.690 -start_high_ends coordinate  -start_high_ends_coordinate 1957.710 -extend_low_ends off -extend_high_ends off -keep_floating_wire_pieces -ignore_parallel_targets -define_parallel_targets_by_wire_directions -mark_as_ring
create_power_straps  -direction vertical  -start_at 215.690 -nets VDD -layer 62 -width 10.000 -start_low_ends coordinate  -start_low_ends_coordinate 210.690 -start_high_ends coordinate  -start_high_ends_coordinate 1957.710 -extend_low_ends off -extend_high_ends off -keep_floating_wire_pieces -ignore_parallel_targets -define_parallel_targets_by_wire_directions -mark_as_ring
create_power_straps  -direction horizontal  -start_at 215.690 -nets VDD -layer 63 -width 10.000 -start_low_ends coordinate  -start_low_ends_coordinate 210.690 -start_high_ends coordinate  -start_high_ends_coordinate 1957.590 -extend_low_ends off -extend_high_ends off -keep_floating_wire_pieces -ignore_parallel_targets -define_parallel_targets_by_wire_directions -mark_as_ring
create_power_straps  -direction horizontal  -start_at 1952.710 -nets VDD -layer 63 -width 10.000 -start_low_ends coordinate  -start_low_ends_coordinate 210.690 -start_high_ends coordinate  -start_high_ends_coordinate 1957.590 -extend_low_ends off -extend_high_ends off -keep_floating_wire_pieces -ignore_parallel_targets -define_parallel_targets_by_wire_directions -mark_as_ring
create_power_straps  -direction vertical  -start_at 1941.930 -nets VSS -layer 62 -width 10.000 -start_low_ends coordinate  -start_low_ends_coordinate 221.300 -start_high_ends coordinate  -start_high_ends_coordinate 1947.100 -extend_low_ends off -extend_high_ends off -keep_floating_wire_pieces -ignore_parallel_targets -define_parallel_targets_by_wire_directions -mark_as_ring
create_power_straps  -direction vertical  -start_at 226.350 -nets VSS -layer 62 -width 10.000 -start_low_ends coordinate  -start_low_ends_coordinate 221.300 -start_high_ends coordinate  -start_high_ends_coordinate 1947.100 -extend_low_ends off -extend_high_ends off -keep_floating_wire_pieces -ignore_parallel_targets -define_parallel_targets_by_wire_directions -mark_as_ring
create_power_straps  -direction horizontal  -start_at 226.300 -nets VSS -layer 63 -width 10.000 -start_low_ends coordinate  -start_low_ends_coordinate 221.350 -start_high_ends coordinate  -start_high_ends_coordinate 1946.930 -extend_low_ends off -extend_high_ends off -keep_floating_wire_pieces -ignore_parallel_targets -define_parallel_targets_by_wire_directions -mark_as_ring
create_power_straps  -direction horizontal  -start_at 1942.100 -nets VSS -layer 63 -width 10.000 -start_low_ends coordinate  -start_low_ends_coordinate 221.350 -start_high_ends coordinate  -start_high_ends_coordinate 1946.930 -extend_low_ends off -extend_high_ends off -keep_floating_wire_pieces -ignore_parallel_targets -define_parallel_targets_by_wire_directions -mark_as_ring
# Starting to commit block rings
# Starting to commit metal4 straps for net VDD
create_power_straps  -direction vertical  -start_at 446.270 -nets VDD  -layer 64 -width 2.000 -pitch_within_group 212.110 -start_low_ends coordinate  -start_low_ends_coordinate 210.690 -start_high_ends coordinate  -start_high_ends_coordinate 1957.710 -extend_low_ends off -extend_high_ends off -num_placement_strap 1 -keep_floating_wire_pieces  -ignore_parallel_targets -define_parallel_targets_by_wire_directions 
create_power_straps  -direction vertical  -start_at 658.790 -nets VDD  -layer 64 -width 2.000 -pitch_within_group 212.110 -start_low_ends coordinate  -start_low_ends_coordinate 210.690 -start_high_ends coordinate  -start_high_ends_coordinate 1957.710 -extend_low_ends off -extend_high_ends off -num_placement_strap 1 -keep_floating_wire_pieces  -ignore_parallel_targets -define_parallel_targets_by_wire_directions 
create_power_straps  -direction vertical  -start_at 870.650 -nets VDD  -layer 64 -width 2.000 -pitch_within_group 212.110 -start_low_ends coordinate  -start_low_ends_coordinate 210.690 -start_high_ends coordinate  -start_high_ends_coordinate 1957.710 -extend_low_ends off -extend_high_ends off -num_placement_strap 1 -keep_floating_wire_pieces  -ignore_parallel_targets -define_parallel_targets_by_wire_directions 
create_power_straps  -direction vertical  -start_at 1082.510 -nets VDD  -layer 64 -width 2.000 -pitch_within_group 212.110 -start_low_ends coordinate  -start_low_ends_coordinate 210.690 -start_high_ends coordinate  -start_high_ends_coordinate 1957.710 -extend_low_ends off -extend_high_ends off -num_placement_strap 1 -keep_floating_wire_pieces  -ignore_parallel_targets -define_parallel_targets_by_wire_directions 
create_power_straps  -direction vertical  -start_at 1295.030 -nets VDD  -layer 64 -width 2.000 -pitch_within_group 212.110 -start_low_ends coordinate  -start_low_ends_coordinate 210.690 -start_high_ends coordinate  -start_high_ends_coordinate 1957.710 -extend_low_ends off -extend_high_ends off -num_placement_strap 1 -keep_floating_wire_pieces  -ignore_parallel_targets -define_parallel_targets_by_wire_directions 
create_power_straps  -direction vertical  -start_at 1506.890 -nets VDD  -layer 64 -width 2.000 -pitch_within_group 212.110 -start_low_ends coordinate  -start_low_ends_coordinate 210.690 -start_high_ends coordinate  -start_high_ends_coordinate 1957.710 -extend_low_ends off -extend_high_ends off -num_placement_strap 1 -keep_floating_wire_pieces  -ignore_parallel_targets -define_parallel_targets_by_wire_directions 
create_power_straps  -direction vertical  -start_at 1719.410 -nets VDD  -layer 64 -width 2.000 -pitch_within_group 212.110 -start_low_ends coordinate  -start_low_ends_coordinate 210.690 -start_high_ends coordinate  -start_high_ends_coordinate 1957.710 -extend_low_ends off -extend_high_ends off -num_placement_strap 1 -keep_floating_wire_pieces  -ignore_parallel_targets -define_parallel_targets_by_wire_directions 
# Starting to commit metal4 straps for net VSS
create_power_straps  -direction vertical  -start_at 448.870 -nets VSS  -layer 64 -width 2.000 -pitch_within_group 212.110 -start_low_ends coordinate  -start_low_ends_coordinate 221.300 -start_high_ends coordinate  -start_high_ends_coordinate 1947.100 -extend_low_ends off -extend_high_ends off -num_placement_strap 1 -keep_floating_wire_pieces  -ignore_parallel_targets -define_parallel_targets_by_wire_directions 
create_power_straps  -direction vertical  -start_at 661.390 -nets VSS  -layer 64 -width 2.000 -pitch_within_group 212.110 -start_low_ends coordinate  -start_low_ends_coordinate 221.300 -start_high_ends coordinate  -start_high_ends_coordinate 1947.100 -extend_low_ends off -extend_high_ends off -num_placement_strap 1 -keep_floating_wire_pieces  -ignore_parallel_targets -define_parallel_targets_by_wire_directions 
create_power_straps  -direction vertical  -start_at 873.250 -nets VSS  -layer 64 -width 2.000 -pitch_within_group 212.110 -start_low_ends coordinate  -start_low_ends_coordinate 221.300 -start_high_ends coordinate  -start_high_ends_coordinate 1947.100 -extend_low_ends off -extend_high_ends off -num_placement_strap 1 -keep_floating_wire_pieces  -ignore_parallel_targets -define_parallel_targets_by_wire_directions 
create_power_straps  -direction vertical  -start_at 1085.110 -nets VSS  -layer 64 -width 2.000 -pitch_within_group 212.110 -start_low_ends coordinate  -start_low_ends_coordinate 221.300 -start_high_ends coordinate  -start_high_ends_coordinate 1947.100 -extend_low_ends off -extend_high_ends off -num_placement_strap 1 -keep_floating_wire_pieces  -ignore_parallel_targets -define_parallel_targets_by_wire_directions 
create_power_straps  -direction vertical  -start_at 1297.630 -nets VSS  -layer 64 -width 2.000 -pitch_within_group 212.110 -start_low_ends coordinate  -start_low_ends_coordinate 221.300 -start_high_ends coordinate  -start_high_ends_coordinate 1947.100 -extend_low_ends off -extend_high_ends off -num_placement_strap 1 -keep_floating_wire_pieces  -ignore_parallel_targets -define_parallel_targets_by_wire_directions 
create_power_straps  -direction vertical  -start_at 1509.490 -nets VSS  -layer 64 -width 2.000 -pitch_within_group 212.110 -start_low_ends coordinate  -start_low_ends_coordinate 221.300 -start_high_ends coordinate  -start_high_ends_coordinate 1947.100 -extend_low_ends off -extend_high_ends off -num_placement_strap 1 -keep_floating_wire_pieces  -ignore_parallel_targets -define_parallel_targets_by_wire_directions 
create_power_straps  -direction vertical  -start_at 1722.010 -nets VSS  -layer 64 -width 2.000 -pitch_within_group 212.110 -start_low_ends coordinate  -start_low_ends_coordinate 221.300 -start_high_ends coordinate  -start_high_ends_coordinate 1947.100 -extend_low_ends off -extend_high_ends off -num_placement_strap 1 -keep_floating_wire_pieces  -ignore_parallel_targets -define_parallel_targets_by_wire_directions 
# Starting to commit metal5 straps for net VDD
create_power_straps  -direction horizontal  -start_at 446.080 -nets VDD  -layer 65 -width 2.000 -pitch_within_group 212.120 -start_low_ends coordinate  -start_low_ends_coordinate 210.690 -start_high_ends coordinate  -start_high_ends_coordinate 1957.590 -extend_low_ends off -extend_high_ends off -num_placement_strap 1 -keep_floating_wire_pieces  -ignore_parallel_targets -define_parallel_targets_by_wire_directions 
create_power_straps  -direction horizontal  -start_at 658.880 -nets VDD  -layer 65 -width 2.000 -pitch_within_group 212.120 -start_low_ends coordinate  -start_low_ends_coordinate 210.690 -start_high_ends coordinate  -start_high_ends_coordinate 1957.590 -extend_low_ends off -extend_high_ends off -num_placement_strap 1 -keep_floating_wire_pieces  -ignore_parallel_targets -define_parallel_targets_by_wire_directions 
create_power_straps  -direction horizontal  -start_at 870.730 -nets VDD  -layer 65 -width 2.000 -pitch_within_group 212.120 -start_low_ends coordinate  -start_low_ends_coordinate 210.690 -start_high_ends coordinate  -start_high_ends_coordinate 1957.590 -extend_low_ends off -extend_high_ends off -num_placement_strap 1 -keep_floating_wire_pieces  -ignore_parallel_targets -define_parallel_targets_by_wire_directions 
create_power_straps  -direction horizontal  -start_at 1082.580 -nets VDD  -layer 65 -width 2.000 -pitch_within_group 212.120 -start_low_ends coordinate  -start_low_ends_coordinate 210.690 -start_high_ends coordinate  -start_high_ends_coordinate 1957.590 -extend_low_ends off -extend_high_ends off -num_placement_strap 1 -keep_floating_wire_pieces  -ignore_parallel_targets -define_parallel_targets_by_wire_directions 
create_power_straps  -direction horizontal  -start_at 1295.380 -nets VDD  -layer 65 -width 2.000 -pitch_within_group 212.120 -start_low_ends coordinate  -start_low_ends_coordinate 210.690 -start_high_ends coordinate  -start_high_ends_coordinate 1957.590 -extend_low_ends off -extend_high_ends off -num_placement_strap 1 -keep_floating_wire_pieces  -ignore_parallel_targets -define_parallel_targets_by_wire_directions 
create_power_straps  -direction horizontal  -start_at 1507.230 -nets VDD  -layer 65 -width 2.000 -pitch_within_group 212.120 -start_low_ends coordinate  -start_low_ends_coordinate 210.690 -start_high_ends coordinate  -start_high_ends_coordinate 1957.590 -extend_low_ends off -extend_high_ends off -num_placement_strap 1 -keep_floating_wire_pieces  -ignore_parallel_targets -define_parallel_targets_by_wire_directions 
create_power_straps  -direction horizontal  -start_at 1719.080 -nets VDD  -layer 65 -width 2.000 -pitch_within_group 212.120 -start_low_ends coordinate  -start_low_ends_coordinate 210.690 -start_high_ends coordinate  -start_high_ends_coordinate 1957.590 -extend_low_ends off -extend_high_ends off -num_placement_strap 1 -keep_floating_wire_pieces  -ignore_parallel_targets -define_parallel_targets_by_wire_directions 
# Starting to commit metal5 straps for net VSS
create_power_straps  -direction horizontal  -start_at 448.680 -nets VSS  -layer 65 -width 2.000 -pitch_within_group 212.120 -start_low_ends coordinate  -start_low_ends_coordinate 221.350 -start_high_ends coordinate  -start_high_ends_coordinate 1946.930 -extend_low_ends off -extend_high_ends off -num_placement_strap 1 -keep_floating_wire_pieces  -ignore_parallel_targets -define_parallel_targets_by_wire_directions 
create_power_straps  -direction horizontal  -start_at 661.480 -nets VSS  -layer 65 -width 2.000 -pitch_within_group 212.120 -start_low_ends coordinate  -start_low_ends_coordinate 221.350 -start_high_ends coordinate  -start_high_ends_coordinate 1946.930 -extend_low_ends off -extend_high_ends off -num_placement_strap 1 -keep_floating_wire_pieces  -ignore_parallel_targets -define_parallel_targets_by_wire_directions 
create_power_straps  -direction horizontal  -start_at 873.330 -nets VSS  -layer 65 -width 2.000 -pitch_within_group 212.120 -start_low_ends coordinate  -start_low_ends_coordinate 221.350 -start_high_ends coordinate  -start_high_ends_coordinate 1946.930 -extend_low_ends off -extend_high_ends off -num_placement_strap 1 -keep_floating_wire_pieces  -ignore_parallel_targets -define_parallel_targets_by_wire_directions 
create_power_straps  -direction horizontal  -start_at 1085.180 -nets VSS  -layer 65 -width 2.000 -pitch_within_group 212.120 -start_low_ends coordinate  -start_low_ends_coordinate 221.350 -start_high_ends coordinate  -start_high_ends_coordinate 1946.930 -extend_low_ends off -extend_high_ends off -num_placement_strap 1 -keep_floating_wire_pieces  -ignore_parallel_targets -define_parallel_targets_by_wire_directions 
create_power_straps  -direction horizontal  -start_at 1297.980 -nets VSS  -layer 65 -width 2.000 -pitch_within_group 212.120 -start_low_ends coordinate  -start_low_ends_coordinate 221.350 -start_high_ends coordinate  -start_high_ends_coordinate 1946.930 -extend_low_ends off -extend_high_ends off -num_placement_strap 1 -keep_floating_wire_pieces  -ignore_parallel_targets -define_parallel_targets_by_wire_directions 
create_power_straps  -direction horizontal  -start_at 1509.830 -nets VSS  -layer 65 -width 2.000 -pitch_within_group 212.120 -start_low_ends coordinate  -start_low_ends_coordinate 221.350 -start_high_ends coordinate  -start_high_ends_coordinate 1946.930 -extend_low_ends off -extend_high_ends off -num_placement_strap 1 -keep_floating_wire_pieces  -ignore_parallel_targets -define_parallel_targets_by_wire_directions 
create_power_straps  -direction horizontal  -start_at 1721.680 -nets VSS  -layer 65 -width 2.000 -pitch_within_group 212.120 -start_low_ends coordinate  -start_low_ends_coordinate 221.350 -start_high_ends coordinate  -start_high_ends_coordinate 1946.930 -extend_low_ends off -extend_high_ends off -num_placement_strap 1 -keep_floating_wire_pieces  -ignore_parallel_targets -define_parallel_targets_by_wire_directions 
set_pns_commit_mode false
