set_pns_commit_mode true
# Starting to commit core rings
create_power_straps  -direction vertical  -start_at 1446.370 -nets VDD -layer 62 -width 10.000 -start_low_ends coordinate  -start_low_ends_coordinate 210.690 -start_high_ends coordinate  -start_high_ends_coordinate 1448.670 -extend_low_ends off -extend_high_ends off -keep_floating_wire_pieces -ignore_parallel_targets -define_parallel_targets_by_wire_directions -mark_as_ring
create_power_straps  -direction vertical  -start_at 215.690 -nets VDD -layer 62 -width 10.000 -start_low_ends coordinate  -start_low_ends_coordinate 210.690 -start_high_ends coordinate  -start_high_ends_coordinate 1448.670 -extend_low_ends off -extend_high_ends off -keep_floating_wire_pieces -ignore_parallel_targets -define_parallel_targets_by_wire_directions -mark_as_ring
create_power_straps  -direction horizontal  -start_at 215.690 -nets VDD -layer 63 -width 10.000 -start_low_ends coordinate  -start_low_ends_coordinate 210.690 -start_high_ends coordinate  -start_high_ends_coordinate 1451.370 -extend_low_ends off -extend_high_ends off -keep_floating_wire_pieces -ignore_parallel_targets -define_parallel_targets_by_wire_directions -mark_as_ring
create_power_straps  -direction horizontal  -start_at 1443.670 -nets VDD -layer 63 -width 10.000 -start_low_ends coordinate  -start_low_ends_coordinate 210.690 -start_high_ends coordinate  -start_high_ends_coordinate 1451.370 -extend_low_ends off -extend_high_ends off -keep_floating_wire_pieces -ignore_parallel_targets -define_parallel_targets_by_wire_directions -mark_as_ring
create_power_straps  -direction vertical  -start_at 1435.710 -nets VSS -layer 62 -width 10.000 -start_low_ends coordinate  -start_low_ends_coordinate 221.300 -start_high_ends coordinate  -start_high_ends_coordinate 1438.060 -extend_low_ends off -extend_high_ends off -keep_floating_wire_pieces -ignore_parallel_targets -define_parallel_targets_by_wire_directions -mark_as_ring
create_power_straps  -direction vertical  -start_at 226.350 -nets VSS -layer 62 -width 10.000 -start_low_ends coordinate  -start_low_ends_coordinate 221.300 -start_high_ends coordinate  -start_high_ends_coordinate 1438.060 -extend_low_ends off -extend_high_ends off -keep_floating_wire_pieces -ignore_parallel_targets -define_parallel_targets_by_wire_directions -mark_as_ring
create_power_straps  -direction horizontal  -start_at 226.300 -nets VSS -layer 63 -width 10.000 -start_low_ends coordinate  -start_low_ends_coordinate 221.350 -start_high_ends coordinate  -start_high_ends_coordinate 1440.710 -extend_low_ends off -extend_high_ends off -keep_floating_wire_pieces -ignore_parallel_targets -define_parallel_targets_by_wire_directions -mark_as_ring
create_power_straps  -direction horizontal  -start_at 1433.060 -nets VSS -layer 63 -width 10.000 -start_low_ends coordinate  -start_low_ends_coordinate 221.350 -start_high_ends coordinate  -start_high_ends_coordinate 1440.710 -extend_low_ends off -extend_high_ends off -keep_floating_wire_pieces -ignore_parallel_targets -define_parallel_targets_by_wire_directions -mark_as_ring
# Starting to commit block rings
# Starting to commit metal4 straps for net VDD
create_power_straps  -direction vertical  -start_at 382.910 -nets VDD  -layer 64 -width 2.000 -pitch_within_group 148.830 -start_low_ends coordinate  -start_low_ends_coordinate 210.690 -start_high_ends coordinate  -start_high_ends_coordinate 1448.670 -extend_low_ends off -extend_high_ends off -num_placement_strap 1 -keep_floating_wire_pieces  -ignore_parallel_targets -define_parallel_targets_by_wire_directions 
create_power_straps  -direction vertical  -start_at 532.070 -nets VDD  -layer 64 -width 2.000 -pitch_within_group 148.830 -start_low_ends coordinate  -start_low_ends_coordinate 210.690 -start_high_ends coordinate  -start_high_ends_coordinate 1448.670 -extend_low_ends off -extend_high_ends off -num_placement_strap 1 -keep_floating_wire_pieces  -ignore_parallel_targets -define_parallel_targets_by_wire_directions 
create_power_straps  -direction vertical  -start_at 680.570 -nets VDD  -layer 64 -width 2.000 -pitch_within_group 148.830 -start_low_ends coordinate  -start_low_ends_coordinate 210.690 -start_high_ends coordinate  -start_high_ends_coordinate 1448.670 -extend_low_ends off -extend_high_ends off -num_placement_strap 1 -keep_floating_wire_pieces  -ignore_parallel_targets -define_parallel_targets_by_wire_directions 
create_power_straps  -direction vertical  -start_at 829.730 -nets VDD  -layer 64 -width 2.000 -pitch_within_group 148.830 -start_low_ends coordinate  -start_low_ends_coordinate 210.690 -start_high_ends coordinate  -start_high_ends_coordinate 1448.670 -extend_low_ends off -extend_high_ends off -num_placement_strap 1 -keep_floating_wire_pieces  -ignore_parallel_targets -define_parallel_targets_by_wire_directions 
create_power_straps  -direction vertical  -start_at 978.230 -nets VDD  -layer 64 -width 2.000 -pitch_within_group 148.830 -start_low_ends coordinate  -start_low_ends_coordinate 210.690 -start_high_ends coordinate  -start_high_ends_coordinate 1448.670 -extend_low_ends off -extend_high_ends off -num_placement_strap 1 -keep_floating_wire_pieces  -ignore_parallel_targets -define_parallel_targets_by_wire_directions 
create_power_straps  -direction vertical  -start_at 1127.390 -nets VDD  -layer 64 -width 2.000 -pitch_within_group 148.830 -start_low_ends coordinate  -start_low_ends_coordinate 210.690 -start_high_ends coordinate  -start_high_ends_coordinate 1448.670 -extend_low_ends off -extend_high_ends off -num_placement_strap 1 -keep_floating_wire_pieces  -ignore_parallel_targets -define_parallel_targets_by_wire_directions 
create_power_straps  -direction vertical  -start_at 1275.890 -nets VDD  -layer 64 -width 2.000 -pitch_within_group 148.830 -start_low_ends coordinate  -start_low_ends_coordinate 210.690 -start_high_ends coordinate  -start_high_ends_coordinate 1448.670 -extend_low_ends off -extend_high_ends off -num_placement_strap 1 -keep_floating_wire_pieces  -ignore_parallel_targets -define_parallel_targets_by_wire_directions 
# Starting to commit metal4 straps for net VSS
create_power_straps  -direction vertical  -start_at 385.510 -nets VSS  -layer 64 -width 2.000 -pitch_within_group 148.830 -start_low_ends coordinate  -start_low_ends_coordinate 221.300 -start_high_ends coordinate  -start_high_ends_coordinate 1438.060 -extend_low_ends off -extend_high_ends off -num_placement_strap 1 -keep_floating_wire_pieces  -ignore_parallel_targets -define_parallel_targets_by_wire_directions 
create_power_straps  -direction vertical  -start_at 534.670 -nets VSS  -layer 64 -width 2.000 -pitch_within_group 148.830 -start_low_ends coordinate  -start_low_ends_coordinate 221.300 -start_high_ends coordinate  -start_high_ends_coordinate 1438.060 -extend_low_ends off -extend_high_ends off -num_placement_strap 1 -keep_floating_wire_pieces  -ignore_parallel_targets -define_parallel_targets_by_wire_directions 
create_power_straps  -direction vertical  -start_at 683.170 -nets VSS  -layer 64 -width 2.000 -pitch_within_group 148.830 -start_low_ends coordinate  -start_low_ends_coordinate 221.300 -start_high_ends coordinate  -start_high_ends_coordinate 1438.060 -extend_low_ends off -extend_high_ends off -num_placement_strap 1 -keep_floating_wire_pieces  -ignore_parallel_targets -define_parallel_targets_by_wire_directions 
create_power_straps  -direction vertical  -start_at 832.330 -nets VSS  -layer 64 -width 2.000 -pitch_within_group 148.830 -start_low_ends coordinate  -start_low_ends_coordinate 221.300 -start_high_ends coordinate  -start_high_ends_coordinate 1438.060 -extend_low_ends off -extend_high_ends off -num_placement_strap 1 -keep_floating_wire_pieces  -ignore_parallel_targets -define_parallel_targets_by_wire_directions 
create_power_straps  -direction vertical  -start_at 980.830 -nets VSS  -layer 64 -width 2.000 -pitch_within_group 148.830 -start_low_ends coordinate  -start_low_ends_coordinate 221.300 -start_high_ends coordinate  -start_high_ends_coordinate 1438.060 -extend_low_ends off -extend_high_ends off -num_placement_strap 1 -keep_floating_wire_pieces  -ignore_parallel_targets -define_parallel_targets_by_wire_directions 
create_power_straps  -direction vertical  -start_at 1129.990 -nets VSS  -layer 64 -width 2.000 -pitch_within_group 148.830 -start_low_ends coordinate  -start_low_ends_coordinate 221.300 -start_high_ends coordinate  -start_high_ends_coordinate 1438.060 -extend_low_ends off -extend_high_ends off -num_placement_strap 1 -keep_floating_wire_pieces  -ignore_parallel_targets -define_parallel_targets_by_wire_directions 
create_power_straps  -direction vertical  -start_at 1278.490 -nets VSS  -layer 64 -width 2.000 -pitch_within_group 148.830 -start_low_ends coordinate  -start_low_ends_coordinate 221.300 -start_high_ends coordinate  -start_high_ends_coordinate 1438.060 -extend_low_ends off -extend_high_ends off -num_placement_strap 1 -keep_floating_wire_pieces  -ignore_parallel_targets -define_parallel_targets_by_wire_directions 
# Starting to commit metal5 straps for net VDD
create_power_straps  -direction horizontal  -start_at 382.430 -nets VDD  -layer 65 -width 2.000 -pitch_within_group 148.490 -start_low_ends coordinate  -start_low_ends_coordinate 210.690 -start_high_ends coordinate  -start_high_ends_coordinate 1451.370 -extend_low_ends off -extend_high_ends off -num_placement_strap 1 -keep_floating_wire_pieces  -ignore_parallel_targets -define_parallel_targets_by_wire_directions 
create_power_straps  -direction horizontal  -start_at 531.580 -nets VDD  -layer 65 -width 2.000 -pitch_within_group 148.490 -start_low_ends coordinate  -start_low_ends_coordinate 210.690 -start_high_ends coordinate  -start_high_ends_coordinate 1451.370 -extend_low_ends off -extend_high_ends off -num_placement_strap 1 -keep_floating_wire_pieces  -ignore_parallel_targets -define_parallel_targets_by_wire_directions 
create_power_straps  -direction horizontal  -start_at 679.780 -nets VDD  -layer 65 -width 2.000 -pitch_within_group 148.490 -start_low_ends coordinate  -start_low_ends_coordinate 210.690 -start_high_ends coordinate  -start_high_ends_coordinate 1451.370 -extend_low_ends off -extend_high_ends off -num_placement_strap 1 -keep_floating_wire_pieces  -ignore_parallel_targets -define_parallel_targets_by_wire_directions 
create_power_straps  -direction horizontal  -start_at 827.980 -nets VDD  -layer 65 -width 2.000 -pitch_within_group 148.490 -start_low_ends coordinate  -start_low_ends_coordinate 210.690 -start_high_ends coordinate  -start_high_ends_coordinate 1451.370 -extend_low_ends off -extend_high_ends off -num_placement_strap 1 -keep_floating_wire_pieces  -ignore_parallel_targets -define_parallel_targets_by_wire_directions 
create_power_straps  -direction horizontal  -start_at 977.130 -nets VDD  -layer 65 -width 2.000 -pitch_within_group 148.490 -start_low_ends coordinate  -start_low_ends_coordinate 210.690 -start_high_ends coordinate  -start_high_ends_coordinate 1451.370 -extend_low_ends off -extend_high_ends off -num_placement_strap 1 -keep_floating_wire_pieces  -ignore_parallel_targets -define_parallel_targets_by_wire_directions 
create_power_straps  -direction horizontal  -start_at 1125.330 -nets VDD  -layer 65 -width 2.000 -pitch_within_group 148.490 -start_low_ends coordinate  -start_low_ends_coordinate 210.690 -start_high_ends coordinate  -start_high_ends_coordinate 1451.370 -extend_low_ends off -extend_high_ends off -num_placement_strap 1 -keep_floating_wire_pieces  -ignore_parallel_targets -define_parallel_targets_by_wire_directions 
create_power_straps  -direction horizontal  -start_at 1273.530 -nets VDD  -layer 65 -width 2.000 -pitch_within_group 148.490 -start_low_ends coordinate  -start_low_ends_coordinate 210.690 -start_high_ends coordinate  -start_high_ends_coordinate 1451.370 -extend_low_ends off -extend_high_ends off -num_placement_strap 1 -keep_floating_wire_pieces  -ignore_parallel_targets -define_parallel_targets_by_wire_directions 
# Starting to commit metal5 straps for net VSS
create_power_straps  -direction horizontal  -start_at 385.030 -nets VSS  -layer 65 -width 2.000 -pitch_within_group 148.490 -start_low_ends coordinate  -start_low_ends_coordinate 221.350 -start_high_ends coordinate  -start_high_ends_coordinate 1440.710 -extend_low_ends off -extend_high_ends off -num_placement_strap 1 -keep_floating_wire_pieces  -ignore_parallel_targets -define_parallel_targets_by_wire_directions 
create_power_straps  -direction horizontal  -start_at 534.180 -nets VSS  -layer 65 -width 2.000 -pitch_within_group 148.490 -start_low_ends coordinate  -start_low_ends_coordinate 221.350 -start_high_ends coordinate  -start_high_ends_coordinate 1440.710 -extend_low_ends off -extend_high_ends off -num_placement_strap 1 -keep_floating_wire_pieces  -ignore_parallel_targets -define_parallel_targets_by_wire_directions 
create_power_straps  -direction horizontal  -start_at 682.380 -nets VSS  -layer 65 -width 2.000 -pitch_within_group 148.490 -start_low_ends coordinate  -start_low_ends_coordinate 221.350 -start_high_ends coordinate  -start_high_ends_coordinate 1440.710 -extend_low_ends off -extend_high_ends off -num_placement_strap 1 -keep_floating_wire_pieces  -ignore_parallel_targets -define_parallel_targets_by_wire_directions 
create_power_straps  -direction horizontal  -start_at 830.580 -nets VSS  -layer 65 -width 2.000 -pitch_within_group 148.490 -start_low_ends coordinate  -start_low_ends_coordinate 221.350 -start_high_ends coordinate  -start_high_ends_coordinate 1440.710 -extend_low_ends off -extend_high_ends off -num_placement_strap 1 -keep_floating_wire_pieces  -ignore_parallel_targets -define_parallel_targets_by_wire_directions 
create_power_straps  -direction horizontal  -start_at 979.730 -nets VSS  -layer 65 -width 2.000 -pitch_within_group 148.490 -start_low_ends coordinate  -start_low_ends_coordinate 221.350 -start_high_ends coordinate  -start_high_ends_coordinate 1440.710 -extend_low_ends off -extend_high_ends off -num_placement_strap 1 -keep_floating_wire_pieces  -ignore_parallel_targets -define_parallel_targets_by_wire_directions 
create_power_straps  -direction horizontal  -start_at 1127.930 -nets VSS  -layer 65 -width 2.000 -pitch_within_group 148.490 -start_low_ends coordinate  -start_low_ends_coordinate 221.350 -start_high_ends coordinate  -start_high_ends_coordinate 1440.710 -extend_low_ends off -extend_high_ends off -num_placement_strap 1 -keep_floating_wire_pieces  -ignore_parallel_targets -define_parallel_targets_by_wire_directions 
create_power_straps  -direction horizontal  -start_at 1276.130 -nets VSS  -layer 65 -width 2.000 -pitch_within_group 148.490 -start_low_ends coordinate  -start_low_ends_coordinate 221.350 -start_high_ends coordinate  -start_high_ends_coordinate 1440.710 -extend_low_ends off -extend_high_ends off -num_placement_strap 1 -keep_floating_wire_pieces  -ignore_parallel_targets -define_parallel_targets_by_wire_directions 
set_pns_commit_mode false
