set_pns_commit_mode true
# Starting to commit core rings
create_power_straps  -direction vertical  -start_at 1876.690 -nets VDD -layer 62 -width 10.000 -start_low_ends coordinate  -start_low_ends_coordinate 210.690 -start_high_ends coordinate  -start_high_ends_coordinate 1881.310 -extend_low_ends off -extend_high_ends off -keep_floating_wire_pieces -ignore_parallel_targets -define_parallel_targets_by_wire_directions -mark_as_ring
create_power_straps  -direction vertical  -start_at 215.690 -nets VDD -layer 62 -width 10.000 -start_low_ends coordinate  -start_low_ends_coordinate 210.690 -start_high_ends coordinate  -start_high_ends_coordinate 1881.310 -extend_low_ends off -extend_high_ends off -keep_floating_wire_pieces -ignore_parallel_targets -define_parallel_targets_by_wire_directions -mark_as_ring
create_power_straps  -direction horizontal  -start_at 215.690 -nets VDD -layer 63 -width 10.000 -start_low_ends coordinate  -start_low_ends_coordinate 210.690 -start_high_ends coordinate  -start_high_ends_coordinate 1881.690 -extend_low_ends off -extend_high_ends off -keep_floating_wire_pieces -ignore_parallel_targets -define_parallel_targets_by_wire_directions -mark_as_ring
create_power_straps  -direction horizontal  -start_at 1876.310 -nets VDD -layer 63 -width 10.000 -start_low_ends coordinate  -start_low_ends_coordinate 210.690 -start_high_ends coordinate  -start_high_ends_coordinate 1881.690 -extend_low_ends off -extend_high_ends off -keep_floating_wire_pieces -ignore_parallel_targets -define_parallel_targets_by_wire_directions -mark_as_ring
create_power_straps  -direction vertical  -start_at 1866.030 -nets VSS -layer 62 -width 10.000 -start_low_ends coordinate  -start_low_ends_coordinate 221.300 -start_high_ends coordinate  -start_high_ends_coordinate 1870.700 -extend_low_ends off -extend_high_ends off -keep_floating_wire_pieces -ignore_parallel_targets -define_parallel_targets_by_wire_directions -mark_as_ring
create_power_straps  -direction vertical  -start_at 226.350 -nets VSS -layer 62 -width 10.000 -start_low_ends coordinate  -start_low_ends_coordinate 221.300 -start_high_ends coordinate  -start_high_ends_coordinate 1870.700 -extend_low_ends off -extend_high_ends off -keep_floating_wire_pieces -ignore_parallel_targets -define_parallel_targets_by_wire_directions -mark_as_ring
create_power_straps  -direction horizontal  -start_at 226.300 -nets VSS -layer 63 -width 10.000 -start_low_ends coordinate  -start_low_ends_coordinate 221.350 -start_high_ends coordinate  -start_high_ends_coordinate 1871.030 -extend_low_ends off -extend_high_ends off -keep_floating_wire_pieces -ignore_parallel_targets -define_parallel_targets_by_wire_directions -mark_as_ring
create_power_straps  -direction horizontal  -start_at 1865.700 -nets VSS -layer 63 -width 10.000 -start_low_ends coordinate  -start_low_ends_coordinate 221.350 -start_high_ends coordinate  -start_high_ends_coordinate 1871.030 -extend_low_ends off -extend_high_ends off -keep_floating_wire_pieces -ignore_parallel_targets -define_parallel_targets_by_wire_directions -mark_as_ring
# Starting to commit block rings
# Starting to commit metal4 straps for net VDD
create_power_straps  -direction vertical  -start_at 437.030 -nets VDD  -layer 64 -width 2.000 -pitch_within_group 202.620 -start_low_ends coordinate  -start_low_ends_coordinate 210.690 -start_high_ends coordinate  -start_high_ends_coordinate 1881.310 -extend_low_ends off -extend_high_ends off -num_placement_strap 1 -keep_floating_wire_pieces  -ignore_parallel_targets -define_parallel_targets_by_wire_directions 
create_power_straps  -direction vertical  -start_at 639.650 -nets VDD  -layer 64 -width 2.000 -pitch_within_group 202.620 -start_low_ends coordinate  -start_low_ends_coordinate 210.690 -start_high_ends coordinate  -start_high_ends_coordinate 1881.310 -extend_low_ends off -extend_high_ends off -num_placement_strap 1 -keep_floating_wire_pieces  -ignore_parallel_targets -define_parallel_targets_by_wire_directions 
create_power_straps  -direction vertical  -start_at 842.270 -nets VDD  -layer 64 -width 2.000 -pitch_within_group 202.620 -start_low_ends coordinate  -start_low_ends_coordinate 210.690 -start_high_ends coordinate  -start_high_ends_coordinate 1881.310 -extend_low_ends off -extend_high_ends off -num_placement_strap 1 -keep_floating_wire_pieces  -ignore_parallel_targets -define_parallel_targets_by_wire_directions 
create_power_straps  -direction vertical  -start_at 1044.890 -nets VDD  -layer 64 -width 2.000 -pitch_within_group 202.620 -start_low_ends coordinate  -start_low_ends_coordinate 210.690 -start_high_ends coordinate  -start_high_ends_coordinate 1881.310 -extend_low_ends off -extend_high_ends off -num_placement_strap 1 -keep_floating_wire_pieces  -ignore_parallel_targets -define_parallel_targets_by_wire_directions 
create_power_straps  -direction vertical  -start_at 1247.510 -nets VDD  -layer 64 -width 2.000 -pitch_within_group 202.620 -start_low_ends coordinate  -start_low_ends_coordinate 210.690 -start_high_ends coordinate  -start_high_ends_coordinate 1881.310 -extend_low_ends off -extend_high_ends off -num_placement_strap 1 -keep_floating_wire_pieces  -ignore_parallel_targets -define_parallel_targets_by_wire_directions 
create_power_straps  -direction vertical  -start_at 1450.130 -nets VDD  -layer 64 -width 2.000 -pitch_within_group 202.620 -start_low_ends coordinate  -start_low_ends_coordinate 210.690 -start_high_ends coordinate  -start_high_ends_coordinate 1881.310 -extend_low_ends off -extend_high_ends off -num_placement_strap 1 -keep_floating_wire_pieces  -ignore_parallel_targets -define_parallel_targets_by_wire_directions 
create_power_straps  -direction vertical  -start_at 1652.750 -nets VDD  -layer 64 -width 2.000 -pitch_within_group 202.620 -start_low_ends coordinate  -start_low_ends_coordinate 210.690 -start_high_ends coordinate  -start_high_ends_coordinate 1881.310 -extend_low_ends off -extend_high_ends off -num_placement_strap 1 -keep_floating_wire_pieces  -ignore_parallel_targets -define_parallel_targets_by_wire_directions 
# Starting to commit metal4 straps for net VSS
create_power_straps  -direction vertical  -start_at 439.630 -nets VSS  -layer 64 -width 2.000 -pitch_within_group 202.620 -start_low_ends coordinate  -start_low_ends_coordinate 221.300 -start_high_ends coordinate  -start_high_ends_coordinate 1870.700 -extend_low_ends off -extend_high_ends off -num_placement_strap 1 -keep_floating_wire_pieces  -ignore_parallel_targets -define_parallel_targets_by_wire_directions 
create_power_straps  -direction vertical  -start_at 642.250 -nets VSS  -layer 64 -width 2.000 -pitch_within_group 202.620 -start_low_ends coordinate  -start_low_ends_coordinate 221.300 -start_high_ends coordinate  -start_high_ends_coordinate 1870.700 -extend_low_ends off -extend_high_ends off -num_placement_strap 1 -keep_floating_wire_pieces  -ignore_parallel_targets -define_parallel_targets_by_wire_directions 
create_power_straps  -direction vertical  -start_at 844.870 -nets VSS  -layer 64 -width 2.000 -pitch_within_group 202.620 -start_low_ends coordinate  -start_low_ends_coordinate 221.300 -start_high_ends coordinate  -start_high_ends_coordinate 1870.700 -extend_low_ends off -extend_high_ends off -num_placement_strap 1 -keep_floating_wire_pieces  -ignore_parallel_targets -define_parallel_targets_by_wire_directions 
create_power_straps  -direction vertical  -start_at 1047.490 -nets VSS  -layer 64 -width 2.000 -pitch_within_group 202.620 -start_low_ends coordinate  -start_low_ends_coordinate 221.300 -start_high_ends coordinate  -start_high_ends_coordinate 1870.700 -extend_low_ends off -extend_high_ends off -num_placement_strap 1 -keep_floating_wire_pieces  -ignore_parallel_targets -define_parallel_targets_by_wire_directions 
create_power_straps  -direction vertical  -start_at 1250.110 -nets VSS  -layer 64 -width 2.000 -pitch_within_group 202.620 -start_low_ends coordinate  -start_low_ends_coordinate 221.300 -start_high_ends coordinate  -start_high_ends_coordinate 1870.700 -extend_low_ends off -extend_high_ends off -num_placement_strap 1 -keep_floating_wire_pieces  -ignore_parallel_targets -define_parallel_targets_by_wire_directions 
create_power_straps  -direction vertical  -start_at 1452.730 -nets VSS  -layer 64 -width 2.000 -pitch_within_group 202.620 -start_low_ends coordinate  -start_low_ends_coordinate 221.300 -start_high_ends coordinate  -start_high_ends_coordinate 1870.700 -extend_low_ends off -extend_high_ends off -num_placement_strap 1 -keep_floating_wire_pieces  -ignore_parallel_targets -define_parallel_targets_by_wire_directions 
create_power_straps  -direction vertical  -start_at 1655.350 -nets VSS  -layer 64 -width 2.000 -pitch_within_group 202.620 -start_low_ends coordinate  -start_low_ends_coordinate 221.300 -start_high_ends coordinate  -start_high_ends_coordinate 1870.700 -extend_low_ends off -extend_high_ends off -num_placement_strap 1 -keep_floating_wire_pieces  -ignore_parallel_targets -define_parallel_targets_by_wire_directions 
# Starting to commit metal5 straps for net VDD
create_power_straps  -direction horizontal  -start_at 436.580 -nets VDD  -layer 65 -width 2.000 -pitch_within_group 202.570 -start_low_ends coordinate  -start_low_ends_coordinate 210.690 -start_high_ends coordinate  -start_high_ends_coordinate 1881.690 -extend_low_ends off -extend_high_ends off -num_placement_strap 1 -keep_floating_wire_pieces  -ignore_parallel_targets -define_parallel_targets_by_wire_directions 
create_power_straps  -direction horizontal  -start_at 639.880 -nets VDD  -layer 65 -width 2.000 -pitch_within_group 202.570 -start_low_ends coordinate  -start_low_ends_coordinate 210.690 -start_high_ends coordinate  -start_high_ends_coordinate 1881.690 -extend_low_ends off -extend_high_ends off -num_placement_strap 1 -keep_floating_wire_pieces  -ignore_parallel_targets -define_parallel_targets_by_wire_directions 
create_power_straps  -direction horizontal  -start_at 842.230 -nets VDD  -layer 65 -width 2.000 -pitch_within_group 202.570 -start_low_ends coordinate  -start_low_ends_coordinate 210.690 -start_high_ends coordinate  -start_high_ends_coordinate 1881.690 -extend_low_ends off -extend_high_ends off -num_placement_strap 1 -keep_floating_wire_pieces  -ignore_parallel_targets -define_parallel_targets_by_wire_directions 
create_power_straps  -direction horizontal  -start_at 1044.580 -nets VDD  -layer 65 -width 2.000 -pitch_within_group 202.570 -start_low_ends coordinate  -start_low_ends_coordinate 210.690 -start_high_ends coordinate  -start_high_ends_coordinate 1881.690 -extend_low_ends off -extend_high_ends off -num_placement_strap 1 -keep_floating_wire_pieces  -ignore_parallel_targets -define_parallel_targets_by_wire_directions 
create_power_straps  -direction horizontal  -start_at 1246.930 -nets VDD  -layer 65 -width 2.000 -pitch_within_group 202.570 -start_low_ends coordinate  -start_low_ends_coordinate 210.690 -start_high_ends coordinate  -start_high_ends_coordinate 1881.690 -extend_low_ends off -extend_high_ends off -num_placement_strap 1 -keep_floating_wire_pieces  -ignore_parallel_targets -define_parallel_targets_by_wire_directions 
create_power_straps  -direction horizontal  -start_at 1450.230 -nets VDD  -layer 65 -width 2.000 -pitch_within_group 202.570 -start_low_ends coordinate  -start_low_ends_coordinate 210.690 -start_high_ends coordinate  -start_high_ends_coordinate 1881.690 -extend_low_ends off -extend_high_ends off -num_placement_strap 1 -keep_floating_wire_pieces  -ignore_parallel_targets -define_parallel_targets_by_wire_directions 
create_power_straps  -direction horizontal  -start_at 1652.580 -nets VDD  -layer 65 -width 2.000 -pitch_within_group 202.570 -start_low_ends coordinate  -start_low_ends_coordinate 210.690 -start_high_ends coordinate  -start_high_ends_coordinate 1881.690 -extend_low_ends off -extend_high_ends off -num_placement_strap 1 -keep_floating_wire_pieces  -ignore_parallel_targets -define_parallel_targets_by_wire_directions 
# Starting to commit metal5 straps for net VSS
create_power_straps  -direction horizontal  -start_at 439.180 -nets VSS  -layer 65 -width 2.000 -pitch_within_group 202.570 -start_low_ends coordinate  -start_low_ends_coordinate 221.350 -start_high_ends coordinate  -start_high_ends_coordinate 1871.030 -extend_low_ends off -extend_high_ends off -num_placement_strap 1 -keep_floating_wire_pieces  -ignore_parallel_targets -define_parallel_targets_by_wire_directions 
create_power_straps  -direction horizontal  -start_at 642.480 -nets VSS  -layer 65 -width 2.000 -pitch_within_group 202.570 -start_low_ends coordinate  -start_low_ends_coordinate 221.350 -start_high_ends coordinate  -start_high_ends_coordinate 1871.030 -extend_low_ends off -extend_high_ends off -num_placement_strap 1 -keep_floating_wire_pieces  -ignore_parallel_targets -define_parallel_targets_by_wire_directions 
create_power_straps  -direction horizontal  -start_at 844.830 -nets VSS  -layer 65 -width 2.000 -pitch_within_group 202.570 -start_low_ends coordinate  -start_low_ends_coordinate 221.350 -start_high_ends coordinate  -start_high_ends_coordinate 1871.030 -extend_low_ends off -extend_high_ends off -num_placement_strap 1 -keep_floating_wire_pieces  -ignore_parallel_targets -define_parallel_targets_by_wire_directions 
create_power_straps  -direction horizontal  -start_at 1047.180 -nets VSS  -layer 65 -width 2.000 -pitch_within_group 202.570 -start_low_ends coordinate  -start_low_ends_coordinate 221.350 -start_high_ends coordinate  -start_high_ends_coordinate 1871.030 -extend_low_ends off -extend_high_ends off -num_placement_strap 1 -keep_floating_wire_pieces  -ignore_parallel_targets -define_parallel_targets_by_wire_directions 
create_power_straps  -direction horizontal  -start_at 1249.530 -nets VSS  -layer 65 -width 2.000 -pitch_within_group 202.570 -start_low_ends coordinate  -start_low_ends_coordinate 221.350 -start_high_ends coordinate  -start_high_ends_coordinate 1871.030 -extend_low_ends off -extend_high_ends off -num_placement_strap 1 -keep_floating_wire_pieces  -ignore_parallel_targets -define_parallel_targets_by_wire_directions 
create_power_straps  -direction horizontal  -start_at 1452.830 -nets VSS  -layer 65 -width 2.000 -pitch_within_group 202.570 -start_low_ends coordinate  -start_low_ends_coordinate 221.350 -start_high_ends coordinate  -start_high_ends_coordinate 1871.030 -extend_low_ends off -extend_high_ends off -num_placement_strap 1 -keep_floating_wire_pieces  -ignore_parallel_targets -define_parallel_targets_by_wire_directions 
create_power_straps  -direction horizontal  -start_at 1655.180 -nets VSS  -layer 65 -width 2.000 -pitch_within_group 202.570 -start_low_ends coordinate  -start_low_ends_coordinate 221.350 -start_high_ends coordinate  -start_high_ends_coordinate 1871.030 -extend_low_ends off -extend_high_ends off -num_placement_strap 1 -keep_floating_wire_pieces  -ignore_parallel_targets -define_parallel_targets_by_wire_directions 
set_pns_commit_mode false
